### ISSUE TITLE
Crash at hijackthis close

### ISSUE THREAD

**Issue by ghost** [dragokas/hijackthis#20] opened 2018-01-31 12:33 UTC
I've tested all the tools and close them. When I close hijackthis I've error starting with double frame... and hijackthis.exe remain running without UI...

That's all folks for today :-)

**Comment by ghost** [comment] 2018-01-31 12:47
Oupss. An error windows remains open and come back indefinitely after clicking OK or no...

**Comment by dragokas** [comment] 2018-01-31 16:38
Hi, BUBBLEIO !

Cannot reproduce.
Please, provide:
1. Link to screenshot of error.
2. Concrete sequence of your actions.
3. OS version, bitness and build you are using.
4. Is antivirus software turned off (doesn't block anything) ?

It is only possible if something prevent HJT from deletion MSCOMCTL.OCX file that will be unpacked near HiJackThis.exe file during launching StartupList2 tool. This Microsoft component is required for its interface. I'm planning to replace it in the nearest future builds. But, for now, please, ensure, if HJT couldn't remove it on its own, can you remove it manually. If no, some software on your PC makes that lock.

Thanks.

**Comment by ghost** [comment] 2018-01-31 16:45
If it appear for other, I will spend time to describe deeper but now I don't have time to.
Anyway don't worry. It's not a big problem and I don't really use it as I said before.

**Comment by dragokas** [comment] 2018-01-31 16:49
There was 1 strange report already.
I will be grateful if you reproduce it in your free time.

**Comment by ghost** [comment] 2018-01-31 22:00
OK. In reality I also had difficulty to reproduce. 
1 - Start Hijackthis
2 - Launch tools\StartupList
3 - Close Hijackthis before StartupList finish to process
4 - Hijackthis crash with messages
----
5 - In my tests, I've also close StartupList window before StartupList finish to process. It should be not possible!! 
6 - And Hijackthis crash again with messages

**Comment by dragokas** [comment] 2018-01-31 22:19
Thanks, BUBBLEIO. Confirmed.
Okay, it will be not easy, but I'll fix it.

**Comment by dragokas** [comment] 2018-02-02 02:47
Fixed in 2.8.0.2.
Test version available by the link: https://dragokas.com/tools/HiJackThis_test.zip

**Closed as completed by dragokas** 2018-02-02 02:47 UTC
Labels: bug

**Comment by ghost** [comment] 2018-02-02 13:58
Working well here. thanx.
