### ISSUE TITLE
Ignorelist not working

### ISSUE THREAD

**Issue by Gordon-Dry** [dragokas/hijackthis#70] opened 2019-05-29 12:14 UTC
On each scan all entries are shown again, no matter if they're already on the ignorelist.
29.0.18
29.0.19

I use HijackThis with StartupDelayer, and the starting of other programs can only continue when HijackThis is finished.
It runs with HijackThis.exe /startupscan and if nothing new is found it should terminate itself.
But it shows everything - again. Which is already on the ignorelist.

Very frustrating.

Should I go back to 2.00.004 ?

**Comment by Sandor-Helper** [comment] 2019-05-29 12:25
Hello and welcome!

Do you want us to do a deep investigation of your system? If so please collect logs as [described here](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F).

**Comment by Gordon-Dry** [comment] 2019-05-29 13:03
No, this is a Github issue "as usual", it is about the software HijackThis itself....

**Comment by Sandor-Helper** [comment] 2019-05-29 13:11
Ok, so wait for Dragokas answer.

**Comment by dragokas** [comment] 2019-05-29 14:40
Hi, and welcome!
Thanks for reporting.

Show, what HJT entries can not hide.

**Comment by Gordon-Dry** [comment] 2019-05-29 15:57
Well, all of them. 
The ignorelist is not saved or ignored itself.

I launch HJT as admin.
And I toggled the setting checkbox about the ignorelist as well. Fails both ways.

**Comment by dragokas** [comment] 2019-05-29 16:05
> And I toggled the setting checkbox about the ignorelist as well. Fails both ways.

Sorry, I don't understand what you mean. 
1. Can you show screenshot?
2. Also, you can't hide specific entry only? Or you can't hide any of the entries?
3. Can you show screenshot of Misc Tools => Ignore list tab?
++ Settings tab...

**Comment by Gordon-Dry** [comment] 2019-05-29 17:44
1.
![Screen-2019-05-29_19-41-01](https://user-images.githubusercontent.com/29145213/58578863-16030c00-824a-11e9-936e-6daaf2fc4951.jpg)

2. can't hide anything

3. there is a lot more stuff below, services I know etc. (I used HJT 2.00.004 for many years)
![Screen-2019-05-29_19-42-03](https://user-images.githubusercontent.com/29145213/58578874-1dc2b080-824a-11e9-8cbd-21b2239ecabd.jpg)

**Comment by dragokas** [comment] 2019-05-29 19:23
Did you add items to ignore list according to this instruction:
https://github.com/dragokas/hijackthis/wiki/HJT:-How-to-add-item-to-ignore-list
?

**Comment by Gordon-Dry** [comment] 2019-05-29 23:05
Yes.
I also tried other variants like rightclick etc.

**Comment by dragokas** [comment] 2019-05-30 10:46
1. Please, make export of this registry key:
`
HKEY_LOCAL_MACHINE\SOFTWARE\TrendMicro
`
pack and attach it to your next post.

Instruction:
How to Export and Import Registry Keys in Windows
https://www.tenforums.com/tutorials/125696-export-import-registry-keys-windows.html

2. Run HiJackThis Fork, press **"Do a system scan and save a log file"**, attach HiJackThis.log

**Comment by Gordon-Dry** [comment] 2019-05-30 14:17
Before I do that I want to tell you what I found:

1. the ignorelist of old HJT is in HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\TrendMicro\HijackThis
2. I was not able to remove it inside HJT no matter old or new version
3. I delete it manually now and try again

**Comment by dragokas** [comment] 2019-05-30 14:33
Registry key of old HiJackThis doesn't affect new HJT Fork.
Please, make HJT log and export of the key exactly as mentioned in my previous post.

**Comment by Gordon-Dry** [comment] 2019-05-30 15:42
Your fork does not only create a registry key
HKEY_LOCAL_MACHINE\SOFTWARE\TrendMicro\HiJackThisFork
but also
HKEY_LOCAL_MACHINE\SOFTWARE\TrendMicro\HiJackThis
and
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\TrendMicro\HiJackThis
which are both empty.
Perhaps your fork tries to look at the wrong places when comparing the findings with the ignore list?

1. HKEY_LOCAL_MACHINE\SOFTWARE\TrendMicro
[HKEY_LOCAL_MACHINE_SOFTWARE_TrendMicro.zip](https://github.com/dragokas/hijackthis/files/3237653/HKEY_LOCAL_MACHINE_SOFTWARE_TrendMicro.zip)

2. HijackThis log ("Prüfung.exe" is the renamed "HijackThis.exe", I do it like that for 10 years to avoid malware recognizing HJT itself by filename):
[HiJackThis.zip](https://github.com/dragokas/hijackthis/files/3237702/HiJackThis.zip)

**Comment by Gordon-Dry** [comment] 2019-05-30 15:48
The most problematic entries which are already in the ignore list but are NOT ignored are these HOSTS entries (other entries from HOSTS are okay and not found again):
![Screen-2019-05-30_17-47-51](https://user-images.githubusercontent.com/29145213/58645173-1e6b4d80-8303-11e9-964a-9552238fa3d2.jpg)

**Comment by dragokas** [comment] 2019-05-30 16:13
Please, also make export of:
`
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion
`
pack and send it to email: dragokas \<at\> safezone.cc
(replace \<at\> with @ )

> Perhaps your fork tries to look at the wrong places when comparing the findings with the ignore list?

No. It is intended for backward compatibility (for license agreement purposes).

**Comment by dragokas** [comment] 2019-07-09 12:28
Are you still there?
Can you complete the last request?

**Comment by Gordon-Dry** [comment] 2019-07-09 12:38
Well, I did that.

**Comment by dragokas** [comment] 2019-08-27 17:06
I didn't receive any email on my address.

**Comment by dragokas** [comment] 2019-09-15 15:24
No answer. Cannot reproduce.

**Comment by Gordon-Dry** [comment] 2019-09-16 22:07
What ever. Months after I sent an eMail you tell me you got none.
Worthless.

**Comment by dragokas** [comment] 2019-09-17 07:33
Please, make a log again and sent it to email: dragokas@safezone.cc
1) HiJackThis log
2) Registry export of
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion

Thank you.

**Comment by dragokas** [comment] 2019-09-17 07:43
Gordon-Dry, I really appreciate your help.
If you have better contact channel I glad to communicate with you directly to resolve this issue quicker.
Have a nice day!

**Comment by Gordon-Dry** [comment] 2023-01-10 21:44
After years of using 2.9.0.26 without issues I dared to update to latest 2.10.0.23 and it shows a nearly same behaviour as mentioned above:
I can add entries to the ignore list - and they are inside that list.
But those entries are not ignored on the next scan if I use the setting "Calculate Checksum".

After deleting the ignorelist, disabling the setting "Calculate Checksum" and starting a new scan and creating a new ignorelist without checksums it worked on the next scan; the entries were ignored as intended.

**Comment by dragokas** [comment] 2023-01-11 00:52
Bug confirmed.
This will be fixed in the next build.
I'll leave this issue opened to inform you when the fix will be ready.

**Comment by dragokas** [comment] 2023-01-11 01:33
Problem fixed, you can download new binary from readme page.

**Closed as completed by dragokas** 2023-01-11 01:33 UTC
Labels: bug
