### ISSUE TITLE
Reporting one issue in StartupList, and another potential issue in AVZ Antivirus Toolkit as well

### ISSUE THREAD

**Issue by Hostn4me** [dragokas/hijackthis#32] opened 2018-07-12 09:45 UTC
Hello,

I would like to report two bugs/errors I encountered in the latest versions of HiJackThis and AVZ Antivirus Toolkit. Before running a full system scan (and saving a log file) within HiJackThis, I decided to run the StartUp List v2.12 Fork. Please refer to the attached screenshot titled "StartupList_Err.png" and you will see that almost halfway through the process, the program throws a Run-time error '5': Invalid procedure call or argument error.

Considering I used to write programs in VB6 a long, long time ago, I'm quite familiar with this error (and I remember it being one of the more common ones, in fact). I'd like to point out that StartupList was in the process of loading my Winlogons Autostarts, as you can clearly see in my screenshot. As instructed, I made sure to generate a debug log file (which is attached as "HiJackThis_debug.log"), although I must admit I only glanced over it for all of about five seconds.

Furthermore, when I was generating the debug log file information using the latest version of the AVZ Antivirus Toolkit, you will see in the attached "RSITx64.exe_Err.png" image that upon AVZ trying to load RSITx64.exe, it was unable to do so. I am not sure if this was due to an issue on my end or otherwise. However, I simply clicked 'OK' and the Toolkit kept humming along as if nothing had ever happened until it finished. Consequently, if this error WAS in fact due to an issue on my end, I'd very much like to know if it would have had anything to do with a potential virus/infection? I am fixing to post my scan log file shortly as I believe it contains quite a few abnormalities.

In conclusion, it would be very simple (for me, at least) to reproduce the two errors I described and displayed above. I would simply run StartupList again (I've run it more than once and the same error occured each time), and the same goes for the AVZ Antivirus Toolkit. I ran it at least twice and the error occurred each time as well. I am assuming the Toolkit error is due to something on my end, although I am unsure about the StartupList error.

Thank you for your time.

![rsitx64 exe_err](https://user-images.githubusercontent.com/30291292/42625779-40c9af5c-858e-11e8-823b-f1d7b327db9e.png)

![startuplist_err](https://user-images.githubusercontent.com/30291292/42625783-4251e326-858e-11e8-941a-cc687e6e61b6.png)

[HiJackThis_debug.log](https://github.com/dragokas/hijackthis/files/2188032/HiJackThis_debug.log)

**Comment by dragokas** [comment] 2018-07-12 17:43
Hi, Hostn4me!
Thank you for detailed report.

Your debug log was partially helpful, because StartupList has no error tracing code yet. I'll prepare it and return to you shortly.

As about RSITx64. tell what Windows version do you use?
0xc000007b (STATUS_INVALID_IMAGE_FORMAT) could happen due to misformatted sections of image or one of the dll loaded by it, including wrong bitness placing, e.g. 32-bit dll located in 64-bit folder (C:\windows\system32). We can try Dependency Walker to track the issue:
 - Download and run as Admin [Dependency Walker x64](http://www.dependencywalker.com)
 - Click File => Open => "...\AutoLogger\RSIT\RSITx64.exe"
 - See and check red errors and warnings. Some of them is normal by default, see: https://prnt.sc/k5q4ei
Please, report if you see some difference compairing to your machine.
 - Also, ensure 'CPU' tab contains 64 bit architecture for all dlls.
 - You can also check machine using **sfc /scannow** console command and provide us "**C:\Windows\Logs\CBS\CBS.log**" log file.

Do you have other suspicions or reasons that your PC is infected?
If so, you can open separate thread in this 'Issue' section by providing CollectionLog by [rules](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F) (you aleady have one) as well as description of your problem.

Kind regards,
Stanislav.

**Comment by dragokas** [comment] 2018-07-12 20:29
Here is a version prepared to catch issue with StartupList: https://dragokas.com/tools/HiJackThis_dbg_test.zip
Please, do the scan and provide screenshot or clipboard text copy of error window.
Thanks.

**ATTENTION:** do not use this HJT version for fixing items.
Bug fix will be available with the nearest official update.

**Comment by Hostn4me** [comment] 2018-07-13 01:44
Hello dragokas,

You are very welcome and thanks for your response! Sorry, I forgot to mention that I am running Windows 10 Pro (64-bit).

I just ran the test version of HiJack Debug that you prepared for me and submitted the error. I also took another screenshot for good measure and I've attached it here as well ("StartupList_Err_2.png").

Yes, I do have scan logs (multiple ones in fact, as I ran multiple scans). As far as why I suspect I am infected, if you don't mind, I'd rather discuss this in private. Is this okay? If so, what is your preferred method of contact?

Thanks again!

![startuplist_err_2](https://user-images.githubusercontent.com/30291292/42668079-56affebc-8614-11e8-9646-25edebb28ccf.png)

**Comment by dragokas** [comment] 2018-07-13 13:51
Hi, Hostn4me !

That function is replaced now. Please, try again: https://dragokas.com/tools/HiJackThis_dbg_test.zip

> Yes, I do have scan logs (multiple ones in fact, as I ran multiple scans). As far as why I suspect I am infected, if you don't mind, I'd rather discuss this in private. Is this okay? If so, what is your preferred method of contact?

You can skype me: ***
However, I'm afraid that we have too different time zones.

**Comment by Hostn4me** [comment] 2018-07-13 20:01
Hello dragokas,

Okay, I will try the new version you posted. Also, the time zones will not be an issue.

Furthermore, I ran the special debug version of HiJackThis that you created for me on a Windows 7 Pro laptop that I have in which I am also afraid may be infected as well. This time (on the laptop), I received a different error while running StartupList. I submitted it to you via the program and I also took a screenshot of the error for good measure, which I have attached to this post.

I will add you on Skype and post again as soon I confirm the Run-time error '5' error has been fixed.

Thanks again!

![win7_startuplist_err](https://user-images.githubusercontent.com/30291292/42711456-8d41a748-86ad-11e8-9550-f7262ed2ebe6.png)

**Comment by dragokas** [comment] 2018-07-14 15:32
It's another one different bug.
Actually, StartupList is never tested enough. Only on very few machines because it's not a part of main engine, it can't fix items, so it can't harm PC.

I can't reproduce issue by registry export you provided.
Please, download again: https://dragokas.com/tools/HiJackThis_dbg_test.zip
Run Startuplist scan and:
1) attach screenshot of error
2) attach HiJackThis_debug.log

Thank you.

**Comment by Hostn4me** [comment] 2018-07-16 12:33
Hello dragokas,

I'm sorry for the slight delay in my response. I ran the updated debug version of HijackThis on Windows 7 Pro (where this particular error occurred). Included below you will find the StartupList debug log along with a screenshot of the error. Furthermore, I will be contacting you again on Skype in a little while,

As always, thanks so much!

[HiJackThis_debug.log](https://github.com/dragokas/hijackthis/files/2197570/HiJackThis_debug.log)

![win7_startuplist_err_2](https://user-images.githubusercontent.com/30291292/42758822-6510bf60-88ca-11e8-8a8d-d3d580e00ef3.png)

**Comment by dragokas** [comment] 2018-07-24 04:49
Hi, Hostn4me !

Please, try run StartupList again: https://dragokas.com/tools/HiJackThis_test2.zip

**Comment by Hostn4me** [comment] 2018-07-27 02:53
Hello dragokas,

I apologize for my late response. Good news, no error this time! I have attached both the debug log and my StartupList below. Please let me know if you need anything else. Lastly, I have been meaning to touch base with you on Skype so I'll be messaging you shortly.

Thanks for all of your help!

[HiJackThis_debug.log](https://github.com/dragokas/hijackthis/files/2234235/HiJackThis_debug.log)

[StartupList.txt](https://github.com/dragokas/hijackthis/files/2234239/StartupList.txt)

**Comment by dragokas** [comment] 2018-07-27 13:14
Thank you. Problem is fixed in v.2.8.0.21 and will go to the nearest release.

**Closed as completed by dragokas** 2018-07-27 13:14 UTC
Labels: bug
