### ISSUE TITLE
Option run at startup doesn't work if hijackthis.exe is already in Fork directory

### ISSUE THREAD

**Issue by ghost** [dragokas/hijackthis#19] opened 2018-01-31 12:31 UTC
Hi,

When I check : Option run at startup it ok if hijackthis.exe is not already in Fork directory. If file is already in fork directory (and run from or not), hijack rename existing hijackthis.exe to xxxx.bak, doesn't create the schedule task and generate an error message.

ps : I just discover the additional tools in Tools menu... that's great!

best...

**Comment by dragokas** [comment] 2018-01-31 15:28
v2.8.0.1 - bug is confirmed. Will be fixed soon. Thanks for reporting.

**Comment by ghost** [comment] 2018-01-31 16:46
Great happy to help your software robustness...

**Comment by dragokas** [comment] 2018-02-02 02:47
Fixed in 2.8.0.2.
Test version available by the link: https://dragokas.com/tools/HiJackThis_test.zip

**Comment by ghost** [comment] 2018-02-02 13:59
Working well for me. thanx.

**Comment by ghost** [comment] 2018-02-02 14:09
Oupps not totally. 
The schedule task has been deleted forever. I've try with hijack in '_c:\_' directory and the '_...fork_' directory deleted nothing happen. 
And that's the same with official version 2.7.0.29!! I'm not able to create the schedule task again???

**Comment by ghost** [comment] 2018-02-02 14:41
In fact, the task exist (with sysinternals autorun) but not in windows 'TaskScheduler' configuration window!

**Comment by dragokas** [comment] 2018-02-02 15:21
What OS version is it?

Please, open elevated command prompt (cmd)
(Ctrl+ Esc -> enter cmd Right click -> Run as admin.)
Enter such command:

> schtasks.exe /create /tn "HiJackThis Autostart Scan" /SC ONSTART /DELAY 0001:00 /F /RL HIGHEST /tr "\\"%ProgramFiles(x86)%\HiJackThis Fork\HiJackThis.exe\\" /startupscan"

What console result message do you see?

**Comment by dragokas** [comment] 2018-02-02 15:36
Is "HiJackThis Autostart Scan" entry visible in O22 of HJT log?

**Comment by ghost** [comment] 2018-02-02 18:42
OK lot of questions and additional test :
- What console result message do you see? Task created ok... - Task is visible in windows task config list and sysinternals autorun and working well after reboot
- Is "HiJackThis Autostart Scan" entry visible in O22 of HJT log? Yes. With cmd and hijack source creation 

Additional tests :
- When I click to enable "Add hijackthis to startup" in your software config screen => Task is created and visible in autorun but not in visible Task in the windows task config list (even after refresh of the list or relaunch of the task config windows) =>After PC reboot, the task is launch and appear visible windows task config list !!!. I've tried with Hijackthis launch 'as administrator" without difference of behaviour.

To conclude : the issue is "only" the visibility of the task when created with hijackthis.exe

**Comment by dragokas** [comment] 2018-02-02 19:16
In such case I have no clue what happens, when you are marking checkbox "Add to startup..." HJT executes the same cmd command as I showed above. And you said cmd work well.
Anyway, since startup item is working after rebooting, and task is visible in O22 and autoruns, looks like function is working properly.
I bet it's something related to problem with Task Scheduler snap-in.

And, you didn't answer, what OS version is it?

**Comment by dragokas** [comment] 2018-02-02 19:54
If the problem still can be reproduced, I'll leave this issues opened, and after finishing priority TODOs, I'll rewrite this function by the native Task Scheduler interface API. Hope, this can help to flush it.

**Comment by ghost** [comment] 2018-02-02 20:02
Windows 10 Pro 16299

**Comment by dragokas** [comment] 2018-02-02 20:52
Ok, confirmed. Thanks.

**Comment by dragokas** [comment] 2018-08-21 20:35
Problem with missing task scheduler record is fixed in [test-build](https://dragokas.com/tools/HiJackThis_test.zip) and will go to the nearest release.

**Closed as completed by dragokas** 2018-08-21 20:35 UTC
Labels: bug
